version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.2.15
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_HEAP_OPTS: "-Xms128M -Xmx128M"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.2.15
    restart: always
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.0.2
    container_name: gateway-redis
    ports:
      - "6379:6379"

  hotel-service:
    extends:
      file: ../hotel-service/docker-compose.yml
      service: hotel-service

  hotel-db:
    extends:
      file: ../hotel-service/docker-compose.yml
      service: hotel-db

  reservation-service:
    extends:
      file: ../reservation-service/docker-compose.yml
      service: reservation-service

  reservation-db:
    extends:
      file: ../reservation-service/docker-compose.yml
      service: reservation-db

  notification-service:
    extends:
      file: ../notification-service/docker-compose.yml
      service: notification-service

  api-gateway:
    extends:
      file: ../api-gateway/docker-compose.yml
      service: api-gateway

  auth-service:
    extends:
      file: ../auth-service/docker-compose.yml
      service: auth-service

  auth-postgres:
    extends:
      file: ../auth-service/docker-compose.yml
      service: auth-postgres

  payment-service:
    extends:
      file: ../payment-service/docker-compose.yml
      service: payment-service

  payment-db:
    extends:
      file: ../payment-service/docker-compose.yml
      service: payment-db

networks:
  hotel-network:
    name: hotel-network
    driver: bridge

volumes:
  postgres-data:
  auth-db-data:
  hotel-db-data:
  reservation-db-data:
  payment-db-data:
